apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: default
spec:
  nodeName: master
  containers:
  - image: httpd:2.4.41-alpine
    name: pod1-container
